import { defineConnector } from './helpers'
import type { CoreveoConnectorDefinition } from '../../types/connectors'

export const BILLING_CONNECTORS: CoreveoConnectorDefinition[] = [
  defineConnector({
    id: 'mind-billing',
    name: 'MIND Billing',
    vendor: 'MIND CTI',
    category: 'Billing & BSS',
    featured: true,
    plgLabel: 'Billing',
    kind: 'pack',
    icon: 'credit-card',
    shortDescription: 'Accounts, services, charges and billing lifecycle.',
    description: 'Telecom billing accounts, subscriptions, charges and payments.',
    overview:
      'MIND Billing provides account, service, product and payment state so Coreveo can compare billing with network and provisioning outcomes.',
    connectionMethods: ['REST API', 'Database Read Access', 'Stored Procedures'],
    connectionType: 'REST API • Database Read Access',
    authMethods: ['API Key', 'Database credentials'],
    entities: ['Customer', 'Account', 'Service', 'Product', 'Invoice', 'Payment'],
    capabilities: [
      'Accounts',
      'Services',
      'Product subscriptions',
      'Billing status',
      'Account status',
      'Charges',
      'Payments',
      'Service lifecycle',
    ],
    actions: [
      { name: 'Lookup Account', governance: 'READ_ONLY' },
      { name: 'Read Billing Status', governance: 'READ_ONLY' },
      { name: 'Read Charges', governance: 'READ_ONLY' },
      { name: 'Adjust Charge', governance: 'APPROVAL_REQUIRED' },
      { name: 'Change Account Status', governance: 'RESTRICTED' },
    ],
    aiCapabilities: { supervisedRemediation: true },
    certificationStatus: 'AVAILABLE',
    useCase:
      'Compare billing state with network state, detect active billing without provisioning, detect provisioned services that are not billed, investigate activation failures, and surface revenue-assurance exceptions.',
    semanticDiscoveries: [
      {
        endpoint: '/accounts/{id}',
        method: 'GET',
        capability: 'Retrieve Billing Account',
        entity: 'Account',
        lifecycleStage: 'Investigation',
        risk: 'Low',
        aiExecution: 'Read Only',
      },
      {
        endpoint: '/services/{id}/status',
        method: 'GET',
        capability: 'Read Service Billing State',
        entity: 'Service',
        lifecycleStage: 'Correlation',
        risk: 'Low',
        aiExecution: 'Read Only',
      },
    ],
  }),
  defineConnector({
    id: 'oracle-brm',
    name: 'Oracle Communications Billing and Revenue Management',
    vendor: 'Oracle',
    category: 'Billing & BSS',
    featured: true,
    kind: 'pack',
    icon: 'credit-card',
    shortDescription: 'Customer accounts, balances, billing and payments.',
    description: 'Oracle BRM accounts, services, balances and payment events.',
    overview:
      'Oracle Communications Billing and Revenue Management supplies customer accounts, services, balances and payment events for billing-to-network correlation.',
    connectionMethods: ['REST / Integration Layer', 'Database', 'Event integration'],
    connectionType: 'REST • Database • Events',
    entities: ['Customer', 'Account', 'Service', 'Balance', 'Payment', 'Product'],
    capabilities: ['Customer accounts', 'Services', 'Balances', 'Billing', 'Payments', 'Products'],
    actions: [
      { name: 'Lookup Account', governance: 'READ_ONLY' },
      { name: 'Read Balance', governance: 'READ_ONLY' },
      { name: 'Apply Adjustment', governance: 'APPROVAL_REQUIRED' },
    ],
    certificationStatus: 'AVAILABLE',
  }),
  defineConnector({
    id: 'amdocs-bss',
    name: 'Amdocs BSS',
    vendor: 'Amdocs',
    category: 'Billing & BSS',
    kind: 'pack',
    icon: 'layers',
    shortDescription: 'Customer management, orders, billing and payments.',
    description: 'Amdocs BSS customer, order and billing state.',
    overview: 'Amdocs BSS covers customer management, orders, billing, product/service state and payments.',
    connectionMethods: ['REST API', 'Integration Layer'],
    connectionType: 'REST • Integration Layer',
    entities: ['Customer', 'Order', 'Service', 'Invoice', 'Payment'],
    capabilities: ['Customer management', 'Orders', 'Billing', 'Product/service state', 'Payments'],
    actions: [
      { name: 'Lookup Customer', governance: 'READ_ONLY' },
      { name: 'Read Order', governance: 'READ_ONLY' },
      { name: 'Update Service State', governance: 'APPROVAL_REQUIRED' },
    ],
    certificationStatus: 'MARKETPLACE_PACK',
  }),
  defineConnector({
    id: 'sap-brim',
    name: 'SAP BRIM',
    vendor: 'SAP',
    category: 'Billing & BSS',
    kind: 'pack',
    icon: 'credit-card',
    shortDescription: 'Subscription billing, charging, invoicing and payments.',
    description: 'SAP Billing and Revenue Innovation Management.',
    overview:
      'SAP BRIM provides subscription billing, charging, invoicing, contract accounts and payments for finance-aware exception investigation.',
    connectionMethods: ['OData', 'RFC', 'Event Mesh'],
    connectionType: 'OData • Events',
    entities: ['Contract Account', 'Subscription', 'Invoice', 'Payment', 'Charge'],
    capabilities: ['Subscription billing', 'Charging', 'Invoicing', 'Contract accounts', 'Payments'],
    actions: [
      { name: 'Read Contract Account', governance: 'READ_ONLY' },
      { name: 'Read Invoice', governance: 'READ_ONLY' },
      { name: 'Post Adjustment', governance: 'APPROVAL_REQUIRED' },
    ],
    certificationStatus: 'AVAILABLE',
  }),
  defineConnector({
    id: 'stripe-billing',
    name: 'Stripe Billing',
    vendor: 'Stripe',
    category: 'Billing & BSS',
    kind: 'pack',
    icon: 'credit-card',
    shortDescription: 'Customers, subscriptions, invoices and payment failures.',
    description: 'Stripe customers, subscriptions, invoices and payment events.',
    overview: 'Stripe Billing exposes customers, subscriptions, invoices and payment failures for revenue and payment-exception correlation.',
    connectionMethods: ['REST API', 'Webhook', 'API key'],
    connectionType: 'REST API • Webhooks • API key',
    authMethods: ['API Key'],
    entities: ['Customer', 'Subscription', 'Invoice', 'Payment'],
    capabilities: ['Customers', 'Subscriptions', 'Invoices', 'Payments', 'Payment failures'],
    supportedEvents: ['invoice.payment_failed', 'customer.subscription.updated'],
    actions: [
      { name: 'Lookup Customer', governance: 'READ_ONLY' },
      { name: 'Read Invoice', governance: 'READ_ONLY' },
      { name: 'Retry Payment', governance: 'APPROVAL_REQUIRED' },
    ],
    certificationStatus: 'AVAILABLE',
  }),
]
