import { defineConnector } from './helpers'
import type { CoreveoConnectorDefinition } from '../../types/connectors'

export const CRM_CONNECTORS: CoreveoConnectorDefinition[] = [
  defineConnector({
    id: 'salesforce',
    name: 'Salesforce',
    vendor: 'Salesforce',
    category: 'CRM',
    featured: true,
    plgLabel: 'CRM',
    kind: 'pack',
    icon: 'building',
    shortDescription: 'Customer, account, case and order context.',
    description: 'Customer lookup, cases, orders and service records for exception correlation.',
    overview:
      'Salesforce provides customer, account, case and order context for Coreveo investigations. Coreveo uses it to determine whether technical exceptions already have customer complaints attached.',
    connectionMethods: ['REST API', 'OAuth 2.0', 'Webhook'],
    connectionType: 'REST API • OAuth 2.0 • Webhooks',
    authMethods: ['OAuth 2.0'],
    entities: ['Customer', 'Account', 'Contact', 'Case', 'Order', 'Service'],
    capabilities: [
      'Customer lookup',
      'Account lookup',
      'Cases',
      'Orders',
      'Service records',
      'Customer contact information',
    ],
    actions: [
      { name: 'Lookup Customer', governance: 'READ_ONLY' },
      { name: 'Lookup Account', governance: 'READ_ONLY' },
      { name: 'Search Cases', governance: 'READ_ONLY' },
      { name: 'Create Case', governance: 'SAFE_TO_AUTOMATE' },
      { name: 'Update Case', governance: 'APPROVAL_REQUIRED' },
    ],
    aiCapabilities: { supervisedRemediation: true },
    certificationStatus: 'AVAILABLE',
    useCase:
      'Coreveo correlates customer complaints with technical exceptions, retrieves account context, detects whether multiple cases share a systemic issue, and can create or update cases after resolution.',
    semanticDiscoveries: [
      {
        endpoint: '/services/data/v60.0/sobjects/Case',
        method: 'GET',
        capability: 'Retrieve Customer Case',
        entity: 'Case',
        lifecycleStage: 'Investigation',
        risk: 'Low',
        aiExecution: 'Read Only',
      },
      {
        endpoint: '/services/data/v60.0/sobjects/Case',
        method: 'POST',
        capability: 'Create Support Case',
        entity: 'Case',
        lifecycleStage: 'Resolution',
        risk: 'Medium',
        aiExecution: 'Safe to Automate',
      },
    ],
  }),
  defineConnector({
    id: 'dynamics-365',
    name: 'Microsoft Dynamics 365',
    vendor: 'Microsoft',
    category: 'CRM',
    featured: true,
    kind: 'pack',
    icon: 'building',
    shortDescription: 'Accounts, contacts, cases and customer activity.',
    description: 'Dynamics 365 customer engagement records for account and case context.',
    overview:
      'Microsoft Dynamics 365 supplies account, contact, case and order activity so Coreveo can attach operational exceptions to the customer record that owns the service.',
    connectionMethods: ['Dataverse API', 'OAuth 2.0', 'Webhook'],
    connectionType: 'Dataverse API • OAuth 2.0 • Webhooks',
    authMethods: ['OAuth 2.0'],
    entities: ['Account', 'Contact', 'Case', 'Order', 'Activity'],
    capabilities: ['Accounts', 'Contacts', 'Cases', 'Orders', 'Customer activity'],
    actions: [
      { name: 'Lookup Account', governance: 'READ_ONLY' },
      { name: 'Search Cases', governance: 'READ_ONLY' },
      { name: 'Create Case', governance: 'SAFE_TO_AUTOMATE' },
      { name: 'Update Case', governance: 'APPROVAL_REQUIRED' },
    ],
    aiCapabilities: { supervisedRemediation: true },
    certificationStatus: 'AVAILABLE',
    useCase: 'Retrieve customer and case context, then update Dynamics after a verified resolution.',
  }),
  defineConnector({
    id: 'hubspot',
    name: 'HubSpot',
    vendor: 'HubSpot',
    category: 'CRM',
    kind: 'pack',
    icon: 'building',
    shortDescription: 'Contacts, companies, deals and tickets.',
    description: 'HubSpot CRM objects for customer and ticket correlation.',
    overview: 'HubSpot provides contacts, companies, deals and tickets that Coreveo can use as supporting customer context.',
    connectionMethods: ['REST API', 'OAuth', 'Webhook'],
    connectionType: 'REST API • OAuth • Webhooks',
    authMethods: ['OAuth 2.0', 'API Key'],
    entities: ['Contact', 'Company', 'Deal', 'Ticket'],
    capabilities: ['Contacts', 'Companies', 'Deals', 'Tickets'],
    actions: [
      { name: 'Lookup Contact', governance: 'READ_ONLY' },
      { name: 'Search Tickets', governance: 'READ_ONLY' },
      { name: 'Create Ticket', governance: 'SAFE_TO_AUTOMATE' },
      { name: 'Update Ticket', governance: 'APPROVAL_REQUIRED' },
    ],
    certificationStatus: 'AVAILABLE',
  }),
]
