import { defineConnector } from './helpers'
import type { CoreveoConnectorDefinition } from '../../types/connectors'

export const ERP_CONNECTORS: CoreveoConnectorDefinition[] = [
  defineConnector({
    id: 'business-central',
    name: 'Microsoft Dynamics 365 Business Central',
    vendor: 'Microsoft',
    category: 'ERP & Finance',
    featured: true,
    kind: 'pack',
    icon: 'calculator',
    shortDescription: 'Customers, invoices, payments and ledger reconciliation.',
    description: 'Business Central customers, invoices, payments and general ledger.',
    overview:
      'Microsoft Dynamics 365 Business Central provides customers, invoices, payments and general-ledger context for billing and payment reconciliation.',
    connectionMethods: ['OData', 'OAuth 2.0'],
    connectionType: 'OData • OAuth 2.0',
    authMethods: ['OAuth 2.0'],
    entities: ['Customer', 'Invoice', 'Payment', 'General Ledger', 'Journal'],
    capabilities: ['Customers', 'Invoices', 'Payments', 'General ledger', 'Financial reconciliation'],
    actions: [
      { name: 'Lookup Customer', governance: 'READ_ONLY' },
      { name: 'Read Invoice', governance: 'READ_ONLY' },
      { name: 'Post Payment', governance: 'APPROVAL_REQUIRED' },
    ],
    aiCapabilities: { supervisedRemediation: true },
    certificationStatus: 'AVAILABLE',
    useCase:
      'Billing/payment reconciliation, detect missing financial synchronization, investigate failed payment posting, and compare billing and ERP states.',
  }),
  defineConnector({
    id: 'sap-s4hana',
    name: 'SAP S/4HANA',
    vendor: 'SAP',
    category: 'ERP & Finance',
    kind: 'pack',
    icon: 'calculator',
    shortDescription: 'Customer, billing, finance, orders and payments.',
    description: 'S/4HANA finance and order-to-cash records.',
    overview: 'SAP S/4HANA supplies customer, billing, finance, order and payment records for enterprise reconciliation.',
    connectionMethods: ['OData', 'RFC', 'Event Mesh'],
    connectionType: 'OData • Events',
    entities: ['Customer', 'Billing Document', 'Order', 'Payment', 'FI Document'],
    capabilities: ['Customer', 'Billing', 'Finance', 'Orders', 'Payments'],
    actions: [
      { name: 'Read Customer', governance: 'READ_ONLY' },
      { name: 'Read Billing Document', governance: 'READ_ONLY' },
      { name: 'Post Document', governance: 'RESTRICTED' },
    ],
    certificationStatus: 'MARKETPLACE_PACK',
  }),
  defineConnector({
    id: 'oracle-erp',
    name: 'Oracle ERP Cloud',
    vendor: 'Oracle',
    category: 'ERP & Finance',
    kind: 'pack',
    icon: 'calculator',
    shortDescription: 'Receivables, payables, customers and payments.',
    description: 'Oracle ERP Cloud financial transactions.',
    overview: 'Oracle ERP Cloud provides receivables, payables, customers, payments and financial transactions.',
    connectionMethods: ['REST API', 'OAuth 2.0'],
    connectionType: 'REST API • OAuth 2.0',
    entities: ['Customer', 'Receivable', 'Payable', 'Payment', 'Financial Transaction'],
    capabilities: ['Receivables', 'Payables', 'Customers', 'Payments', 'Financial transactions'],
    actions: [
      { name: 'Read Receivable', governance: 'READ_ONLY' },
      { name: 'Read Payment', governance: 'READ_ONLY' },
      { name: 'Create Payment', governance: 'APPROVAL_REQUIRED' },
    ],
    certificationStatus: 'AVAILABLE',
  }),
]
