import { defineConnector } from './helpers'
import type { CoreveoConnectorDefinition } from '../../types/connectors'

export const GENERIC_CONNECTORS: CoreveoConnectorDefinition[] = [
  defineConnector({
    id: 'rest-api',
    name: 'REST API',
    category: 'Generic APIs',
    featured: true,
    kind: 'generic',
    icon: 'globe',
    shortDescription: 'OpenAPI, OAuth, API key, basic auth and mTLS.',
    description: 'Generic REST connector for systems that are not pre-packaged.',
    overview:
      'The REST API connector lets operators onboard any HTTP system. After importing an OpenAPI contract, Coreveo performs semantic discovery so endpoints become operational capabilities — not just URLs.',
    connectionMethods: ['OpenAPI / Swagger', 'OAuth', 'API Key', 'Basic Auth', 'mTLS'],
    connectionType: 'OpenAPI • OAuth • API Key • mTLS',
    authMethods: ['OAuth 2.0', 'API Key', 'Basic Auth', 'mTLS'],
    entities: ['Resource', 'Customer', 'Order', 'Event'],
    capabilities: ['Import OpenAPI', 'Discover capabilities', 'Map entities', 'Invoke with governance'],
    actions: [
      { name: 'GET resource', governance: 'READ_ONLY' },
      { name: 'POST resource', governance: 'APPROVAL_REQUIRED' },
      { name: 'DELETE resource', governance: 'RESTRICTED' },
    ],
    certificationStatus: 'AVAILABLE',
    useCase: 'Onboard a vendor or internal API that is not yet in the marketplace pack catalog.',
    semanticDiscoveries: [
      {
        endpoint: '/subscriber',
        method: 'POST',
        capability: 'Create Network Subscriber',
        entity: 'Subscriber',
        lifecycleStage: 'Provisioning',
        risk: 'Medium',
        aiExecution: 'Approval Required',
      },
      {
        endpoint: '/accounts/{id}',
        method: 'GET',
        capability: 'Retrieve Billing Account',
        entity: 'Account',
        lifecycleStage: 'Investigation',
        risk: 'Low',
        aiExecution: 'Read Only',
      },
    ],
  }),
  defineConnector({
    id: 'soap-api',
    name: 'SOAP API',
    category: 'Generic APIs',
    kind: 'generic',
    icon: 'file-code',
    shortDescription: 'WSDL import, basic auth and certificate authentication.',
    description: 'Generic SOAP connector for legacy OSS/BSS interfaces.',
    overview: 'Import a WSDL to discover SOAP operations, then map them to Coreveo entities and governance.',
    connectionMethods: ['WSDL import', 'Basic Auth', 'Certificate Authentication'],
    connectionType: 'SOAP • WSDL',
    authMethods: ['Basic Auth', 'Certificate'],
    entities: ['Operation', 'Message', 'Entity'],
    capabilities: ['WSDL import', 'Operation discovery', 'Entity mapping'],
    actions: [
      { name: 'Invoke Query Operation', governance: 'READ_ONLY' },
      { name: 'Invoke Update Operation', governance: 'APPROVAL_REQUIRED' },
    ],
    certificationStatus: 'AVAILABLE',
  }),
  defineConnector({
    id: 'database-generic',
    name: 'Database',
    category: 'Databases',
    kind: 'generic',
    icon: 'database',
    shortDescription: 'Oracle, PostgreSQL, SQL Server and MySQL.',
    description: 'Generic database connector with read-only defaults.',
    overview:
      'Coreveo recommends read-only database access for operational investigation. INSERT, UPDATE and DELETE remain restricted by default.',
    connectionMethods: ['Oracle', 'PostgreSQL', 'SQL Server', 'MySQL'],
    connectionType: 'SQL (read-only)',
    entities: ['Table', 'View', 'Procedure'],
    capabilities: ['Read-only queries', 'Operational state lookup', 'Historical analysis'],
    actions: [
      { name: 'SELECT', governance: 'READ_ONLY' },
      { name: 'Stored Procedure Read', governance: 'READ_ONLY' },
      { name: 'INSERT', governance: 'RESTRICTED' },
      { name: 'UPDATE', governance: 'RESTRICTED' },
      { name: 'DELETE', governance: 'RESTRICTED' },
    ],
    certificationStatus: 'AVAILABLE',
    databaseReadOnlyNote: true,
  }),
  defineConnector({
    id: 'webhook',
    name: 'Webhook',
    category: 'Generic APIs',
    kind: 'generic',
    icon: 'webhook',
    shortDescription: 'Inbound event subscriptions for exception triggers.',
    description: 'Receive vendor or internal events into Coreveo.',
    overview: 'Webhooks let external systems notify Coreveo when a business event may have failed.',
    connectionMethods: ['HTTPS POST', 'HMAC signature'],
    connectionType: 'HTTPS Webhook',
    entities: ['Event', 'Payload'],
    capabilities: ['Inbound events', 'Signature verification', 'Event mapping'],
    actions: [{ name: 'Receive Event', governance: 'READ_ONLY' }],
    certificationStatus: 'AVAILABLE',
  }),
  defineConnector({
    id: 'sftp',
    name: 'SFTP / File Exchange',
    category: 'Generic APIs',
    kind: 'generic',
    icon: 'folder-sync',
    shortDescription: 'Batch files for reconciliations and partner feeds.',
    description: 'Secure file exchange for batch operational feeds.',
    overview: 'SFTP / File Exchange is used for partner and billing batch files. Write/delete of remote files is restricted in the demo.',
    connectionMethods: ['SFTP', 'SSH key'],
    connectionType: 'SFTP',
    entities: ['File', 'Batch', 'Record'],
    capabilities: ['List files', 'Read files', 'Parse delimited records'],
    actions: [
      { name: 'List Files', governance: 'READ_ONLY' },
      { name: 'Read File', governance: 'READ_ONLY' },
      { name: 'Delete File', governance: 'RESTRICTED' },
    ],
    certificationStatus: 'COMING_SOON',
  }),
  defineConnector({
    id: 'syslog',
    name: 'Syslog / Logs',
    category: 'Observability',
    kind: 'generic',
    icon: 'scroll',
    shortDescription: 'Syslog intake for network and application events.',
    description: 'Generic syslog collector for operational evidence.',
    overview: 'Syslog / Logs provides a generic intake path for network and application events.',
    connectionMethods: ['Syslog UDP/TCP', 'TLS syslog'],
    connectionType: 'Syslog',
    entities: ['Log Event', 'Host', 'Facility'],
    capabilities: ['Receive syslog', 'Parse events', 'Search recent logs'],
    actions: [{ name: 'Search Logs', governance: 'READ_ONLY' }],
    certificationStatus: 'COMING_SOON',
  }),
  defineConnector({
    id: 'rabbitmq-generic',
    name: 'RabbitMQ Generic',
    category: 'Messaging',
    kind: 'generic',
    icon: 'messages',
    shortDescription: 'Generic AMQP endpoint when a pack is not used.',
    description: 'Generic RabbitMQ connection for custom vhosts and queues.',
    overview: 'Use RabbitMQ Generic when the broker is not the certified pack instance.',
    connectionMethods: ['Management API', 'AMQP'],
    connectionType: 'Management API',
    entities: ['Queue', 'Message', 'Exchange'],
    capabilities: ['Inspect queue', 'Inspect message'],
    actions: [
      { name: 'Inspect Queue', governance: 'READ_ONLY' },
      { name: 'Purge Queue', governance: 'RESTRICTED' },
    ],
    certificationStatus: 'AVAILABLE',
  }),
  defineConnector({
    id: 'kafka-generic',
    name: 'Kafka Generic',
    category: 'Messaging',
    kind: 'generic',
    icon: 'messages',
    shortDescription: 'Generic Kafka cluster for custom topics.',
    description: 'Generic Kafka connector for topics outside the certified pack.',
    overview: 'Kafka Generic connects to a custom cluster for topic and lag inspection.',
    connectionMethods: ['Admin API', 'Consumer'],
    connectionType: 'Admin API',
    entities: ['Topic', 'Consumer Group', 'Event'],
    capabilities: ['Topics', 'Lag', 'Events'],
    actions: [
      { name: 'List Topics', governance: 'READ_ONLY' },
      { name: 'Reset Offset', governance: 'RESTRICTED' },
    ],
    certificationStatus: 'AVAILABLE',
  }),
]
