import { defineConnector } from './helpers'
import type { CoreveoConnectorDefinition } from '../../types/connectors'

export const ITSM_CONNECTORS: CoreveoConnectorDefinition[] = [
  defineConnector({
    id: 'servicenow',
    name: 'ServiceNow',
    vendor: 'ServiceNow',
    category: 'ITSM',
    featured: true,
    connectedByDefault: true,
    plgLabel: 'ServiceNow',
    kind: 'pack',
    icon: 'headset',
    shortDescription: 'Incidents, problems, change and CMDB context.',
    description: 'Incident, problem, change and CMDB records for investigation and escalation.',
    overview:
      'ServiceNow provides incident, problem, change and CMDB context for Coreveo investigations.',
    connectionMethods: ['REST API', 'OAuth 2.0', 'Basic authentication', 'Webhook'],
    connectionType: 'REST API • OAuth 2.0 • Webhooks',
    authMethods: ['OAuth 2.0', 'Basic authentication'],
    entities: ['Incident', 'Problem', 'Change', 'Configuration Item', 'Knowledge Article', 'Service Request'],
    capabilities: [
      'Incidents',
      'Problems',
      'Changes',
      'CMDB',
      'Service requests',
      'Knowledge articles',
    ],
    actions: [
      { name: 'Read Incident', governance: 'READ_ONLY' },
      { name: 'Search Knowledge', governance: 'READ_ONLY' },
      { name: 'Create Incident', governance: 'SAFE_TO_AUTOMATE' },
      { name: 'Update Incident', governance: 'APPROVAL_REQUIRED' },
      { name: 'Close Incident', governance: 'APPROVAL_REQUIRED' },
    ],
    aiCapabilities: { supervisedRemediation: true },
    certificationStatus: 'CERTIFIED',
    useCase:
      'Coreveo detects 38 wireless activation failures. It searches ServiceNow and finds an incident from two weeks earlier with the same provisioning error. Historical resolution: update the HSS API endpoint and retry failed activations. Coreveo uses this evidence to improve its current diagnosis.',
    semanticDiscoveries: [
      {
        endpoint: '/api/now/table/incident',
        method: 'GET',
        capability: 'Search Related Incidents',
        entity: 'Incident',
        lifecycleStage: 'Investigation',
        risk: 'Low',
        aiExecution: 'Read Only',
      },
      {
        endpoint: '/api/now/table/incident',
        method: 'POST',
        capability: 'Create Engineering Escalation',
        entity: 'Incident',
        lifecycleStage: 'Resolution',
        risk: 'Medium',
        aiExecution: 'Safe to Automate',
      },
    ],
  }),
  defineConnector({
    id: 'jira-sm',
    name: 'Jira Service Management',
    vendor: 'Atlassian',
    category: 'ITSM',
    kind: 'pack',
    icon: 'ticket',
    shortDescription: 'Issues, service requests, incidents and comments.',
    description: 'Jira Service Management issues and service requests for escalations.',
    overview:
      'Jira Service Management holds issues, service requests and incident comments that Coreveo can search and update during supervised resolution.',
    connectionMethods: ['REST API', 'OAuth 2.0', 'API Token'],
    connectionType: 'REST API • OAuth 2.0',
    authMethods: ['OAuth 2.0', 'API Token'],
    entities: ['Issue', 'Service Request', 'Incident', 'Comment', 'Project'],
    capabilities: ['Issues', 'Service requests', 'Incidents', 'Comments', 'Projects'],
    actions: [
      { name: 'Search Issues', governance: 'READ_ONLY' },
      { name: 'Create Issue', governance: 'SAFE_TO_AUTOMATE' },
      { name: 'Add Comment', governance: 'APPROVAL_REQUIRED' },
      { name: 'Transition Issue', governance: 'APPROVAL_REQUIRED' },
    ],
    certificationStatus: 'AVAILABLE',
  }),
  defineConnector({
    id: 'zendesk',
    name: 'Zendesk',
    vendor: 'Zendesk',
    category: 'ITSM',
    kind: 'pack',
    icon: 'headset',
    shortDescription: 'Tickets, users, organizations and comments.',
    description: 'Customer-support tickets and organization records.',
    overview:
      'Zendesk supplies tickets, users and organizations so Coreveo can attach operational exceptions to existing customer-support work.',
    connectionMethods: ['REST API', 'OAuth 2.0', 'Webhook'],
    connectionType: 'REST API • OAuth 2.0 • Webhooks',
    entities: ['Ticket', 'User', 'Organization', 'Comment'],
    capabilities: ['Tickets', 'Users', 'Organizations', 'Comments'],
    actions: [
      { name: 'Read Ticket', governance: 'READ_ONLY' },
      { name: 'Create Ticket', governance: 'SAFE_TO_AUTOMATE' },
      { name: 'Update Ticket', governance: 'APPROVAL_REQUIRED' },
    ],
    certificationStatus: 'AVAILABLE',
  }),
]
