import { defineConnector } from './helpers'
import type { CoreveoConnectorDefinition } from '../../types/connectors'

export const MESSAGING_CONNECTORS: CoreveoConnectorDefinition[] = [
  defineConnector({
    id: 'rabbitmq',
    name: 'RabbitMQ',
    vendor: 'Broadcom',
    category: 'Messaging',
    featured: true,
    kind: 'pack',
    icon: 'messages',
    shortDescription: 'Queues, dead-letter inspection and consumer state.',
    description: 'Queue monitoring, message lookup and retry-pattern detection.',
    overview:
      'RabbitMQ lets Coreveo inspect queues, messages, dead-letter queues and consumer state without operating the broker as infrastructure.',
    connectionMethods: ['Management API', 'AMQP (read)'],
    connectionType: 'Management API • AMQP',
    entities: ['Queue', 'Message', 'Consumer', 'Exchange', 'Dead Letter'],
    capabilities: ['Queue monitoring', 'Message lookup', 'Dead-letter queues', 'Delivery state', 'Consumer state'],
    actions: [
      { name: 'Inspect Queue', governance: 'READ_ONLY' },
      { name: 'Inspect Message', governance: 'READ_ONLY' },
      { name: 'Replay Message', governance: 'APPROVAL_REQUIRED' },
      { name: 'Purge Queue', governance: 'RESTRICTED' },
    ],
    aiCapabilities: { supervisedRemediation: true },
    certificationStatus: 'CERTIFIED',
    useCase:
      'Identify messages stuck in queue, correlate failed events to a business transaction, detect repeated retry patterns, and check consumer availability.',
    semanticDiscoveries: [
      {
        endpoint: '/api/queues/{vhost}/{name}',
        method: 'GET',
        capability: 'Inspect Queue Depth',
        entity: 'Queue',
        lifecycleStage: 'Investigation',
        risk: 'Low',
        aiExecution: 'Read Only',
      },
      {
        endpoint: '/api/queues/{vhost}/{name}/get',
        method: 'POST',
        capability: 'Inspect Message',
        entity: 'Message',
        lifecycleStage: 'Investigation',
        risk: 'Low',
        aiExecution: 'Read Only',
      },
    ],
  }),
  defineConnector({
    id: 'kafka',
    name: 'Apache Kafka',
    vendor: 'Apache',
    category: 'Messaging',
    kind: 'pack',
    icon: 'messages',
    shortDescription: 'Topics, consumer groups, lag and failed processing.',
    description: 'Kafka topics, consumer lag and event inspection.',
    overview: 'Apache Kafka provides topics, consumer groups, events, lag and failed-processing signals for event-driven exceptions.',
    connectionMethods: ['Admin API', 'Consumer (read)'],
    connectionType: 'Admin API • Consumer',
    entities: ['Topic', 'Consumer Group', 'Event', 'Partition'],
    capabilities: ['Topics', 'Consumer groups', 'Events', 'Lag', 'Failed processing'],
    actions: [
      { name: 'List Topics', governance: 'READ_ONLY' },
      { name: 'Read Lag', governance: 'READ_ONLY' },
      { name: 'Reset Offset', governance: 'RESTRICTED' },
    ],
    certificationStatus: 'AVAILABLE',
  }),
  defineConnector({
    id: 'mulesoft',
    name: 'MuleSoft',
    vendor: 'Salesforce',
    category: 'Messaging',
    kind: 'pack',
    icon: 'workflow',
    shortDescription: 'APIs, flows, integration logs and policies.',
    description: 'MuleSoft API and flow observability for integration failures.',
    overview: 'MuleSoft exposes APIs, flows, integration logs and API policies that Coreveo can use when an exception originates in middleware.',
    connectionMethods: ['Anypoint API', 'OAuth 2.0'],
    connectionType: 'Anypoint API • OAuth 2.0',
    entities: ['API', 'Flow', 'Policy', 'Log Event'],
    capabilities: ['APIs', 'Flows', 'Integration logs', 'API policies'],
    actions: [
      { name: 'Read Flow Logs', governance: 'READ_ONLY' },
      { name: 'Inspect Policy', governance: 'READ_ONLY' },
    ],
    certificationStatus: 'AVAILABLE',
  }),
  defineConnector({
    id: 'boomi',
    name: 'Boomi',
    vendor: 'Boomi',
    category: 'Messaging',
    kind: 'pack',
    icon: 'workflow',
    shortDescription: 'Integration processes and execution history.',
    description: 'Boomi process execution and connector logs.',
    overview: 'Boomi provides integration-process execution history for failed or delayed business transactions.',
    connectionMethods: ['REST API', 'Atom API'],
    connectionType: 'REST API',
    entities: ['Process', 'Execution', 'Connector'],
    capabilities: ['Process executions', 'Connector logs', 'Error payloads'],
    actions: [
      { name: 'Read Execution', governance: 'READ_ONLY' },
      { name: 'Rerun Process', governance: 'APPROVAL_REQUIRED' },
    ],
    certificationStatus: 'AVAILABLE',
  }),
]
