import { defineConnector } from './helpers'
import type { CoreveoConnectorDefinition } from '../../types/connectors'

export const OBSERVABILITY_CONNECTORS: CoreveoConnectorDefinition[] = [
  defineConnector({
    id: 'datadog',
    name: 'Datadog',
    vendor: 'Datadog',
    category: 'Observability',
    featured: true,
    kind: 'pack',
    icon: 'activity',
    shortDescription: 'Logs, metrics, traces, alerts and service health.',
    description: 'Datadog telemetry for exception evidence.',
    overview:
      'Datadog provides logs, metrics, traces, alerts and service health that Coreveo uses as supporting evidence — not as a replacement for business-transaction reconstruction.',
    connectionMethods: ['REST API', 'API Key'],
    connectionType: 'REST API • API Key',
    authMethods: ['API Key'],
    entities: ['Log', 'Metric', 'Trace', 'Alert', 'Service'],
    capabilities: ['Logs', 'Metrics', 'Traces', 'Alerts', 'Service health'],
    actions: [
      { name: 'Search Logs', governance: 'READ_ONLY' },
      { name: 'Read Metrics', governance: 'READ_ONLY' },
      { name: 'Read Trace', governance: 'READ_ONLY' },
    ],
    certificationStatus: 'AVAILABLE',
  }),
  defineConnector({
    id: 'splunk',
    name: 'Splunk',
    vendor: 'Splunk',
    category: 'Observability',
    kind: 'pack',
    icon: 'activity',
    shortDescription: 'Search logs, events, alerts and dashboards.',
    description: 'Splunk log search and SIEM events.',
    overview: 'Splunk is used to search logs, events, alerts and dashboards during investigation.',
    connectionMethods: ['REST API', 'Token'],
    connectionType: 'REST API',
    entities: ['Event', 'Alert', 'Dashboard', 'Index'],
    capabilities: ['Search logs', 'Events', 'Alerts', 'Dashboards'],
    actions: [{ name: 'Search Events', governance: 'READ_ONLY' }],
    certificationStatus: 'AVAILABLE',
  }),
  defineConnector({
    id: 'elastic',
    name: 'Elastic / Elasticsearch',
    vendor: 'Elastic',
    category: 'Observability',
    kind: 'pack',
    icon: 'activity',
    shortDescription: 'Logs, search and application events.',
    description: 'Elasticsearch log and event search.',
    overview: 'Elastic / Elasticsearch provides log search and application events for correlation.',
    connectionMethods: ['REST API', 'API Key'],
    connectionType: 'REST API',
    entities: ['Index', 'Document', 'Log Event'],
    capabilities: ['Logs', 'Search', 'Application events'],
    actions: [{ name: 'Search Index', governance: 'READ_ONLY' }],
    certificationStatus: 'AVAILABLE',
  }),
  defineConnector({
    id: 'grafana',
    name: 'Grafana',
    vendor: 'Grafana Labs',
    category: 'Observability',
    kind: 'pack',
    icon: 'activity',
    shortDescription: 'Metrics, dashboards, alerts and data sources.',
    description: 'Grafana dashboards and alert context.',
    overview: 'Grafana exposes metrics, dashboards, alerts and data sources as supporting operational evidence.',
    connectionMethods: ['REST API', 'Service Account'],
    connectionType: 'REST API',
    entities: ['Dashboard', 'Alert', 'Metric', 'Data Source'],
    capabilities: ['Metrics', 'Dashboards', 'Alerts', 'Data sources'],
    actions: [
      { name: 'Read Dashboard', governance: 'READ_ONLY' },
      { name: 'Read Alert', governance: 'READ_ONLY' },
    ],
    certificationStatus: 'AVAILABLE',
  }),
]
