import { defineConnector } from './helpers'
import type { CoreveoConnectorDefinition } from '../../types/connectors'

export const TELECOM_CONNECTORS: CoreveoConnectorDefinition[] = [
  defineConnector({
    id: 'titan-hss',
    name: 'Titan HSS',
    vendor: 'Titan',
    category: 'Telecom',
    featured: true,
    connectedByDefault: true,
    plgLabel: 'HSS',
    kind: 'pack',
    icon: 'radio',
    shortDescription: 'Subscriber lookup, create, suspend and resume.',
    description: 'Home subscriber server identity, authentication and service profile.',
    overview:
      'Titan HSS is the network subscriber system Coreveo queries during activation investigations. Lookup is read-only; create, suspend and resume require approval; delete is restricted.',
    connectionMethods: ['REST API', 'OAuth 2.0'],
    connectionType: 'REST API • OAuth 2.0',
    authMethods: ['OAuth 2.0', 'mTLS'],
    entities: ['MSISDN', 'IMSI', 'ICCID', 'Subscriber', 'Service Profile'],
    capabilities: [
      'Subscriber lookup',
      'Create subscriber',
      'Subscriber status',
      'Suspend',
      'Resume',
      'Delete subscriber',
    ],
    lifecycleStages: ['Provisioning', 'Active', 'Suspended', 'Deleted'],
    actions: [
      { name: 'Lookup Subscriber', governance: 'READ_ONLY' },
      { name: 'Create Subscriber', governance: 'APPROVAL_REQUIRED' },
      { name: 'Suspend Subscriber', governance: 'APPROVAL_REQUIRED' },
      { name: 'Resume Subscriber', governance: 'APPROVAL_REQUIRED' },
      { name: 'Delete Subscriber', governance: 'RESTRICTED' },
    ],
    aiCapabilities: { supervisedRemediation: true },
    certificationStatus: 'CERTIFIED',
    useCase:
      'The hero demo uses Titan HSS to confirm a subscriber was never created after a provisioning API 404, then proposes a supervised retry once the endpoint is corrected.',
    semanticDiscoveries: [
      {
        endpoint: '/subscriber',
        method: 'POST',
        capability: 'Create Network Subscriber',
        entity: 'Subscriber',
        lifecycleStage: 'Provisioning',
        risk: 'Medium',
        aiExecution: 'Approval Required',
      },
      {
        endpoint: '/subscribers/{msisdn}',
        method: 'GET',
        capability: 'Lookup Network Subscriber',
        entity: 'Subscriber',
        lifecycleStage: 'Investigation',
        risk: 'Low',
        aiExecution: 'Read Only',
      },
    ],
  }),
  defineConnector({
    id: 'cisco-broadworks',
    name: 'Cisco BroadWorks',
    vendor: 'Cisco',
    category: 'Telecom',
    featured: true,
    plgLabel: 'Provisioning',
    kind: 'pack',
    icon: 'phone',
    shortDescription: 'User, service and number provisioning.',
    description: 'BroadWorks user, feature and enterprise provisioning.',
    overview:
      'Cisco BroadWorks provides user provisioning, calling features, phone numbers and enterprise/group configuration for voice-service exceptions.',
    connectionMethods: ['OCI-P', 'REST API', 'SOAP'],
    connectionType: 'OCI-P • REST • SOAP',
    entities: ['User', 'Enterprise', 'Group', 'Phone Number', 'Service'],
    capabilities: [
      'User provisioning',
      'Service provisioning',
      'Phone numbers',
      'Calling features',
      'Enterprise/group configuration',
    ],
    actions: [
      { name: 'Lookup User', governance: 'READ_ONLY' },
      { name: 'Provision User', governance: 'APPROVAL_REQUIRED' },
      { name: 'Assign Number', governance: 'APPROVAL_REQUIRED' },
      { name: 'Delete User', governance: 'RESTRICTED' },
    ],
    aiCapabilities: { supervisedRemediation: true },
    certificationStatus: 'AVAILABLE',
  }),
  defineConnector({
    id: 'metaswitch',
    name: 'Metaswitch',
    vendor: 'Metaswitch',
    category: 'Telecom',
    kind: 'pack',
    icon: 'phone',
    shortDescription: 'Subscriber, DID, routing and voice service state.',
    description: 'Metaswitch subscriber and voice routing provisioning.',
    overview: 'Metaswitch covers subscriber, DID, routing and voice-service provisioning state.',
    connectionMethods: ['REST API', 'SOAP'],
    connectionType: 'REST • SOAP',
    entities: ['Subscriber', 'DID', 'Route', 'Voice Service'],
    capabilities: ['Subscriber', 'DID', 'Routing', 'Voice service provisioning', 'Service state'],
    actions: [
      { name: 'Lookup Subscriber', governance: 'READ_ONLY' },
      { name: 'Update Route', governance: 'APPROVAL_REQUIRED' },
    ],
    certificationStatus: 'AVAILABLE',
  }),
  defineConnector({
    id: 'twilio',
    name: 'Twilio',
    vendor: 'Twilio',
    category: 'Telecom',
    kind: 'pack',
    icon: 'phone',
    shortDescription: 'Phone numbers, messaging, voice, SIP and usage.',
    description: 'CPaaS numbers, messaging, voice and SIP usage.',
    overview: 'Twilio is a CPaaS connector for phone numbers, messaging, voice, SIP and usage — operational context, not infrastructure management.',
    connectionMethods: ['REST API', 'Webhook', 'API Key'],
    connectionType: 'REST API • Webhooks',
    entities: ['Phone Number', 'Message', 'Call', 'SIP Domain'],
    capabilities: ['Phone numbers', 'Messaging', 'Voice', 'SIP', 'Usage'],
    actions: [
      { name: 'Lookup Number', governance: 'READ_ONLY' },
      { name: 'Read Usage', governance: 'READ_ONLY' },
      { name: 'Release Number', governance: 'APPROVAL_REQUIRED' },
    ],
    certificationStatus: 'AVAILABLE',
  }),
  defineConnector({
    id: 'did-inventory',
    name: 'DID Inventory & Routing',
    vendor: 'Coreveo',
    category: 'Telecom',
    featured: true,
    connectedByDefault: true,
    plgLabel: 'DID Inventory',
    plgFree: true,
    kind: 'native',
    icon: 'hash',
    shortDescription: 'Number inventory, assignment, routing and release.',
    description: 'Native DID inventory and routing used in Coreveo investigations.',
    overview:
      'DID Inventory & Routing is a Coreveo-native system for number inventory, reservation, assignment, routing and release. It is the free connected system in the demo commercial model.',
    connectionMethods: ['Native Coreveo API'],
    connectionType: 'Coreveo Native',
    entities: ['DID', 'Customer', 'Account', 'Order', 'Carrier', 'Switch', 'Route'],
    capabilities: [
      'Number inventory',
      'Reserve number',
      'Assign number',
      'Route number',
      'Read routing state',
      'Release number',
    ],
    lifecycleStages: ['Available', 'Reserved', 'Assigned', 'Routed', 'Active', 'Released'],
    actions: [
      { name: 'Read Inventory', governance: 'READ_ONLY' },
      { name: 'Read Routing State', governance: 'READ_ONLY' },
      { name: 'Assign Number', governance: 'APPROVAL_REQUIRED' },
      { name: 'Route Number', governance: 'APPROVAL_REQUIRED' },
      { name: 'Release Number', governance: 'RESTRICTED' },
    ],
    aiCapabilities: { supervisedRemediation: true },
    certificationStatus: 'COREVEO_NATIVE',
    useCase: 'DID is assigned and billing is active, but no switch route exists. Coreveo detects the lifecycle break and recommends completing routing after validation.',
  }),
]
